// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZooShop.Data;

#nullable disable

namespace ZooShop.Migrations
{
    [DbContext(typeof(ZooShopDbContext))]
    partial class ZooShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZooShop.Models.AnimalType", b =>
                {
                    b.Property<int>("AnimalTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimalTypeID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnimalTypeID");

                    b.ToTable("AnimalTypes");

                    b.HasData(
                        new
                        {
                            AnimalTypeID = 1,
                            Description = "Товары для собак",
                            TypeName = "Собаки"
                        },
                        new
                        {
                            AnimalTypeID = 2,
                            Description = "Товары для кошек",
                            TypeName = "Кошки"
                        },
                        new
                        {
                            AnimalTypeID = 3,
                            Description = "Товары для птиц",
                            TypeName = "Птицы"
                        },
                        new
                        {
                            AnimalTypeID = 4,
                            Description = "Товары для рыбок",
                            TypeName = "Рыбки"
                        },
                        new
                        {
                            AnimalTypeID = 5,
                            Description = "Товары для грызунов",
                            TypeName = "Грызуны"
                        });
                });

            modelBuilder.Entity("ZooShop.Models.Brand", b =>
                {
                    b.Property<int>("BrandID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandID"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrandID");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            BrandID = 1,
                            BrandName = "Royal Canin",
                            Country = "Франция",
                            Website = "www.royalcanin.com"
                        },
                        new
                        {
                            BrandID = 2,
                            BrandName = "Pro Plan",
                            Country = "США",
                            Website = "www.proplan.ru"
                        },
                        new
                        {
                            BrandID = 3,
                            BrandName = "Pedigree",
                            Country = "США",
                            Website = "www.pedigree.ru"
                        },
                        new
                        {
                            BrandID = 4,
                            BrandName = "Whiskas",
                            Country = "США",
                            Website = "www.whiskas.ru"
                        },
                        new
                        {
                            BrandID = 5,
                            BrandName = "Trixie",
                            Country = "Германия",
                            Website = "www.trixie.de"
                        });
                });

            modelBuilder.Entity("ZooShop.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryID")
                        .HasColumnType("int");

                    b.HasKey("CategoryID");

                    b.HasIndex("ParentCategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Корма"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Игрушки"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Аксессуары"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Лакомства"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Сухие корма",
                            ParentCategoryID = 1
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Влажные корма",
                            ParentCategoryID = 1
                        },
                        new
                        {
                            CategoryID = 7,
                            CategoryName = "Мячики",
                            ParentCategoryID = 2
                        },
                        new
                        {
                            CategoryID = 8,
                            CategoryName = "Лежанки",
                            ParentCategoryID = 3
                        });
                });

            modelBuilder.Entity("ZooShop.Models.Client", b =>
                {
                    b.Property<int>("ClientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientID"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiscountCardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ClientID");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientID = 1,
                            BirthDate = new DateTime(1985, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountCardNumber = "ZS-00123",
                            Email = "elena@mail.ru",
                            FirstName = "Елена",
                            LastName = "Смирнова",
                            Notes = "Постоянный клиент",
                            Phone = "+7-926-100-20-30",
                            RegistrationDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClientID = 2,
                            BirthDate = new DateTime(1990, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountCardNumber = "ZS-00124",
                            Email = "dmitry@mail.ru",
                            FirstName = "Дмитрий",
                            LastName = "Волков",
                            Notes = "Предпочитает натуральные корма",
                            Phone = "+7-926-200-30-40",
                            RegistrationDate = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ZooShop.Models.CurrentStock", b =>
                {
                    b.Property<int?>("CurrentQuantity")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WarehouseID")
                        .HasColumnType("int");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("vw_CurrentStock", (string)null);
                });

            modelBuilder.Entity("ZooShop.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeID = 1,
                            Email = "anna@zooshop.ru",
                            FirstName = "Анна",
                            IsActive = true,
                            LastName = "Петрова",
                            MiddleName = "Ивановна",
                            PasswordHash = "hash1",
                            Phone = "+7-916-111-22-33",
                            Position = "Продавец",
                            Role = "Сотрудник"
                        },
                        new
                        {
                            EmployeeID = 2,
                            Email = "ivan@zooshop.ru",
                            FirstName = "Иван",
                            IsActive = true,
                            LastName = "Сидоров",
                            MiddleName = "Петрович",
                            PasswordHash = "hash2",
                            Phone = "+7-916-222-33-44",
                            Position = "Продавец",
                            Role = "Сотрудник"
                        },
                        new
                        {
                            EmployeeID = 3,
                            Email = "maria@zooshop.ru",
                            FirstName = "Мария",
                            IsActive = true,
                            LastName = "Козлова",
                            MiddleName = "Сергеевна",
                            PasswordHash = "hash3",
                            Phone = "+7-916-333-44-55",
                            Position = "Администратор",
                            Role = "Админ"
                        });
                });

            modelBuilder.Entity("ZooShop.Models.InventoryMovement", b =>
                {
                    b.Property<int>("MovementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovementID"));

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("MovementDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WarehouseID")
                        .HasColumnType("int");

                    b.HasKey("MovementID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("ProductID");

                    b.HasIndex("WarehouseID");

                    b.ToTable("InventoryMovements");

                    b.HasData(
                        new
                        {
                            MovementID = 1,
                            DocumentNumber = "НАКЛ-001",
                            EmployeeID = 3,
                            MovementDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovementType = "IN",
                            Notes = "Первичная приёмка",
                            ProductID = 1,
                            Quantity = 50,
                            UnitPrice = 3000m,
                            WarehouseID = 1
                        },
                        new
                        {
                            MovementID = 2,
                            DocumentNumber = "ПЕР-001",
                            EmployeeID = 3,
                            MovementDate = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovementType = "TRANSFER",
                            Notes = "Перемещение в магазин",
                            ProductID = 1,
                            Quantity = 15,
                            WarehouseID = 2
                        },
                        new
                        {
                            MovementID = 3,
                            DocumentNumber = "НАКЛ-002",
                            EmployeeID = 3,
                            MovementDate = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovementType = "IN",
                            Notes = "Первичная приёмка",
                            ProductID = 2,
                            Quantity = 100,
                            UnitPrice = 800m,
                            WarehouseID = 1
                        },
                        new
                        {
                            MovementID = 4,
                            DocumentNumber = "ПЕР-002",
                            EmployeeID = 3,
                            MovementDate = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovementType = "TRANSFER",
                            Notes = "Перемещение в магазин",
                            ProductID = 2,
                            Quantity = 30,
                            WarehouseID = 2
                        },
                        new
                        {
                            MovementID = 5,
                            DocumentNumber = "НАКЛ-003",
                            EmployeeID = 3,
                            MovementDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovementType = "IN",
                            Notes = "Приёмка игрушек",
                            ProductID = 3,
                            Quantity = 40,
                            UnitPrice = 400m,
                            WarehouseID = 2
                        },
                        new
                        {
                            MovementID = 6,
                            DocumentNumber = "НАКЛ-004",
                            EmployeeID = 3,
                            MovementDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovementType = "IN",
                            Notes = "Приёмка влажных кормов",
                            ProductID = 4,
                            Quantity = 80,
                            UnitPrice = 600m,
                            WarehouseID = 1
                        },
                        new
                        {
                            MovementID = 7,
                            DocumentNumber = "ПЕР-003",
                            EmployeeID = 3,
                            MovementDate = new DateTime(2026, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovementType = "TRANSFER",
                            Notes = "Перемещение в магазин",
                            ProductID = 4,
                            Quantity = 25,
                            WarehouseID = 2
                        },
                        new
                        {
                            MovementID = 8,
                            DocumentNumber = "НАКЛ-005",
                            EmployeeID = 3,
                            MovementDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovementType = "IN",
                            Notes = "Приёмка аксессуаров",
                            ProductID = 5,
                            Quantity = 10,
                            UnitPrice = 2200m,
                            WarehouseID = 2
                        });
                });

            modelBuilder.Entity("ZooShop.Models.Pet", b =>
                {
                    b.Property<int>("PetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PetID"));

                    b.Property<string>("Allergies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AnimalTypeID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Breed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientID")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialNeeds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PetID");

                    b.HasIndex("AnimalTypeID");

                    b.HasIndex("ClientID");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            PetID = 1,
                            Allergies = "Курица",
                            AnimalTypeID = 2,
                            BirthDate = new DateTime(2023, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Breed = "Британская короткошёрстная",
                            ClientID = 1,
                            Gender = "Мальчик",
                            PetName = "Барсик",
                            SpecialNeeds = "Диета для чувствительного пищеварения",
                            Weight = 5.2m
                        },
                        new
                        {
                            PetID = 2,
                            Allergies = "",
                            AnimalTypeID = 1,
                            BirthDate = new DateTime(2022, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Breed = "Немецкая овчарка",
                            ClientID = 1,
                            Gender = "Мальчик",
                            PetName = "Рекс",
                            SpecialNeeds = "",
                            Weight = 32.0m
                        },
                        new
                        {
                            PetID = 3,
                            Allergies = "Рыба, курица",
                            AnimalTypeID = 2,
                            BirthDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Breed = "Персидская",
                            ClientID = 2,
                            Gender = "Девочка",
                            PetName = "Муся",
                            SpecialNeeds = "Ежедневный уход за шерстью",
                            Weight = 3.8m
                        });
                });

            modelBuilder.Entity("ZooShop.Models.PriceHistory", b =>
                {
                    b.Property<int>("PriceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriceID"));

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.HasKey("PriceID");

                    b.HasIndex("ProductID");

                    b.ToTable("PriceHistory");

                    b.HasData(
                        new
                        {
                            PriceID = 1,
                            EffectiveDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 4500m,
                            ProductID = 1
                        },
                        new
                        {
                            PriceID = 2,
                            EffectiveDate = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1200m,
                            ProductID = 2
                        },
                        new
                        {
                            PriceID = 3,
                            EffectiveDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 650m,
                            ProductID = 3
                        },
                        new
                        {
                            PriceID = 4,
                            EffectiveDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 890m,
                            ProductID = 4
                        },
                        new
                        {
                            PriceID = 5,
                            EffectiveDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 3200m,
                            ProductID = 5
                        });
                });

            modelBuilder.Entity("ZooShop.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int?>("AnimalTypeID")
                        .HasColumnType("int");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BrandID")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Composition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SKU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductID");

                    b.HasIndex("AnimalTypeID");

                    b.HasIndex("BrandID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            AnimalTypeID = 1,
                            BrandID = 1,
                            CategoryID = 5,
                            Composition = "Курица, рис, кукуруза, витамины A/D3/E",
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Сухой корм для взрослых собак средних пород (9-25 кг)",
                            IsActive = true,
                            ProductName = "Royal Canin для собак средних пород, 10кг",
                            SKU = "RC-DOG-001",
                            Unit = "шт"
                        },
                        new
                        {
                            ProductID = 2,
                            AnimalTypeID = 2,
                            BrandID = 2,
                            CategoryID = 6,
                            Composition = "Лосось, подсолнечное масло, минералы",
                            CreatedAt = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Влажный корм для стерилизованных кошек",
                            IsActive = true,
                            ProductName = "Pro Plan для кошек стерилизованных, 1.5кг",
                            SKU = "PP-CAT-002",
                            Unit = "шт"
                        },
                        new
                        {
                            ProductID = 3,
                            AnimalTypeID = 1,
                            BrandID = 5,
                            CategoryID = 7,
                            Composition = "Резина, хлопок",
                            CreatedAt = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Прочный резиновый мяч с верёвкой для активных игр",
                            IsActive = true,
                            ProductName = "Мяч Trixie для собак с верёвкой",
                            SKU = "TR-BALL-003",
                            Unit = "шт"
                        },
                        new
                        {
                            ProductID = 4,
                            AnimalTypeID = 2,
                            BrandID = 4,
                            CategoryID = 6,
                            Composition = "Курица, бульон, загустители, витамины",
                            CreatedAt = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Влажный корм для взрослых кошек с курицей в соусе",
                            IsActive = true,
                            ProductName = "Whiskas паучи с курицей, набор 12шт",
                            SKU = "WH-CAT-004",
                            Unit = "уп"
                        },
                        new
                        {
                            ProductID = 5,
                            AnimalTypeID = 1,
                            BrandID = 1,
                            CategoryID = 8,
                            Composition = "Полиэстер, поролон",
                            CreatedAt = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Мягкая лежанка для собак и кошек с антистрессовым покрытием",
                            IsActive = true,
                            ProductName = "Лежанка Royal Canin мягкая, 60x40см",
                            SKU = "RC-BED-005",
                            Unit = "шт"
                        });
                });

            modelBuilder.Entity("ZooShop.Models.Sale", b =>
                {
                    b.Property<int>("SaleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleID"));

                    b.Property<int?>("ClientID")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("EmailSent")
                        .HasColumnType("bit");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrinted")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WarehouseID")
                        .HasColumnType("int");

                    b.HasKey("SaleID");

                    b.HasIndex("ClientID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("WarehouseID");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("ZooShop.Models.SaleItem", b =>
                {
                    b.Property<int>("SaleItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleItemID"));

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SaleID")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SaleItemID");

                    b.HasIndex("ProductID");

                    b.HasIndex("SaleID");

                    b.ToTable("SaleItems");
                });

            modelBuilder.Entity("ZooShop.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleID"));

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<bool>("IsWorked")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("ShiftEnd")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("ShiftStart")
                        .HasColumnType("time");

                    b.Property<string>("ShiftType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ScheduleID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            ScheduleID = 1,
                            EmployeeID = 1,
                            IsWorked = true,
                            ShiftEnd = new TimeSpan(0, 18, 0, 0, 0),
                            ShiftStart = new TimeSpan(0, 9, 0, 0, 0),
                            ShiftType = "Утренняя",
                            WorkDate = new DateTime(2026, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ScheduleID = 2,
                            EmployeeID = 2,
                            IsWorked = true,
                            ShiftEnd = new TimeSpan(0, 21, 0, 0, 0),
                            ShiftStart = new TimeSpan(0, 12, 0, 0, 0),
                            ShiftType = "Вечерняя",
                            WorkDate = new DateTime(2026, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ScheduleID = 3,
                            EmployeeID = 3,
                            IsWorked = true,
                            ShiftEnd = new TimeSpan(0, 18, 0, 0, 0),
                            ShiftStart = new TimeSpan(0, 9, 0, 0, 0),
                            ShiftType = "Полный день",
                            WorkDate = new DateTime(2026, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ScheduleID = 4,
                            EmployeeID = 1,
                            IsWorked = false,
                            ShiftEnd = new TimeSpan(0, 18, 0, 0, 0),
                            ShiftStart = new TimeSpan(0, 9, 0, 0, 0),
                            ShiftType = "Утренняя",
                            WorkDate = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ScheduleID = 5,
                            EmployeeID = 2,
                            IsWorked = false,
                            ShiftEnd = new TimeSpan(0, 18, 0, 0, 0),
                            ShiftStart = new TimeSpan(0, 9, 0, 0, 0),
                            ShiftType = "Полный день",
                            WorkDate = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ZooShop.Models.TodaySales", b =>
                {
                    b.Property<decimal?>("AvgCheck")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NetRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalSales")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_TodaySales", (string)null);
                });

            modelBuilder.Entity("ZooShop.Models.Warehouse", b =>
                {
                    b.Property<int>("WarehouseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WarehouseID"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WarehouseID");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            WarehouseID = 1,
                            Address = "ул. Складская, 10",
                            Phone = "+7-495-111-22-33",
                            WarehouseName = "Основной склад"
                        },
                        new
                        {
                            WarehouseID = 2,
                            Address = "ул. Зоологическая, 5",
                            Phone = "+7-495-444-55-66",
                            WarehouseName = "Магазин №1"
                        });
                });

            modelBuilder.Entity("ZooShop.Models.ZooTask", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskID"));

                    b.Property<int>("AssignedTo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaskID");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            TaskID = 1,
                            AssignedTo = 1,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 3,
                            Description = "Принять и разместить на складе 200 единиц корма Royal Canin",
                            DueDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Высокий",
                            Status = "Новая",
                            TaskTitle = "Приёмка новой партии кормов"
                        },
                        new
                        {
                            TaskID = 2,
                            AssignedTo = 2,
                            CreatedAt = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 3,
                            Description = "Обновить экспозицию кормов и аксессуаров",
                            DueDate = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Средний",
                            Status = "В работе",
                            TaskTitle = "Выкладка товаров в зале"
                        },
                        new
                        {
                            TaskID = 3,
                            AssignedTo = 3,
                            CreatedAt = new DateTime(2026, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 3,
                            Description = "Провести полную инвентаризацию основного склада",
                            DueDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Высокий",
                            Status = "Новая",
                            TaskTitle = "Инвентаризация склада"
                        },
                        new
                        {
                            TaskID = 4,
                            AssignedTo = 1,
                            CompletedDate = new DateTime(2026, 4, 5, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 3,
                            Description = "Ежедневная уборка торгового зала",
                            DueDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Низкий",
                            Status = "Выполнена",
                            TaskTitle = "Уборка в зале"
                        });
                });

            modelBuilder.Entity("ZooShop.Models.Category", b =>
                {
                    b.HasOne("ZooShop.Models.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryID");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("ZooShop.Models.InventoryMovement", b =>
                {
                    b.HasOne("ZooShop.Models.Employee", "Employee")
                        .WithMany("InventoryMovements")
                        .HasForeignKey("EmployeeID");

                    b.HasOne("ZooShop.Models.Product", "Product")
                        .WithMany("InventoryMovements")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooShop.Models.Warehouse", "Warehouse")
                        .WithMany("InventoryMovements")
                        .HasForeignKey("WarehouseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("ZooShop.Models.Pet", b =>
                {
                    b.HasOne("ZooShop.Models.AnimalType", "AnimalType")
                        .WithMany("Pets")
                        .HasForeignKey("AnimalTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooShop.Models.Client", "Client")
                        .WithMany("Pets")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnimalType");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ZooShop.Models.PriceHistory", b =>
                {
                    b.HasOne("ZooShop.Models.Product", "Product")
                        .WithMany("PriceHistory")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ZooShop.Models.Product", b =>
                {
                    b.HasOne("ZooShop.Models.AnimalType", "AnimalType")
                        .WithMany("Products")
                        .HasForeignKey("AnimalTypeID");

                    b.HasOne("ZooShop.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandID");

                    b.HasOne("ZooShop.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID");

                    b.Navigation("AnimalType");

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ZooShop.Models.Sale", b =>
                {
                    b.HasOne("ZooShop.Models.Client", "Client")
                        .WithMany("Sales")
                        .HasForeignKey("ClientID");

                    b.HasOne("ZooShop.Models.Employee", "Employee")
                        .WithMany("Sales")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooShop.Models.Warehouse", "Warehouse")
                        .WithMany("Sales")
                        .HasForeignKey("WarehouseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Employee");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("ZooShop.Models.SaleItem", b =>
                {
                    b.HasOne("ZooShop.Models.Product", "Product")
                        .WithMany("SaleItems")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooShop.Models.Sale", "Sale")
                        .WithMany("SaleItems")
                        .HasForeignKey("SaleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("ZooShop.Models.Schedule", b =>
                {
                    b.HasOne("ZooShop.Models.Employee", "Employee")
                        .WithMany("Schedules")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ZooShop.Models.ZooTask", b =>
                {
                    b.HasOne("ZooShop.Models.Employee", "AssignedEmployee")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ZooShop.Models.Employee", "Creator")
                        .WithMany("CreatedTasks")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedEmployee");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("ZooShop.Models.AnimalType", b =>
                {
                    b.Navigation("Pets");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("ZooShop.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ZooShop.Models.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("ZooShop.Models.Client", b =>
                {
                    b.Navigation("Pets");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("ZooShop.Models.Employee", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("CreatedTasks");

                    b.Navigation("InventoryMovements");

                    b.Navigation("Sales");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("ZooShop.Models.Product", b =>
                {
                    b.Navigation("InventoryMovements");

                    b.Navigation("PriceHistory");

                    b.Navigation("SaleItems");
                });

            modelBuilder.Entity("ZooShop.Models.Sale", b =>
                {
                    b.Navigation("SaleItems");
                });

            modelBuilder.Entity("ZooShop.Models.Warehouse", b =>
                {
                    b.Navigation("InventoryMovements");

                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
